theme = "base16"

[editor]
bufferline = "multiple"
idle-timeout = 50
completion-timeout = 50
gutters = ["diagnostics", "coverage", "line-numbers", "diff"]
#gutters = ["diagnostics", "line-numbers", "coverage", "diff"]
end-of-line-diagnostics = "info"
# [editor.whitespace]
# render = "all"
auto-save.focus-lost = true
[editor.auto-save.after-delay]
enable = true
timeout = 3000
[editor.soft-wrap]
enable = true
[editor.indent-guides]
render = true
[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[keys.normal]
C-a = "code_action"
K = "half_page_up"
J = "half_page_down"
"," = ["goto_prev_diag", "code_action"]
# to help with list indenting S-tab to indent list item and C-tab to dedent
C-tab = "@<esc>I<tab><esc>gl"
S-tab = "@<esc>I<backspace><esc>gl"

[keys.select]
K = "half_page_up"
J = "half_page_down"

[keys.insert]
C-a = "code_action"
C-tab = "@<esc>I<tab><esc>A"
S-tab = "@<esc>I<backspace><esc>A"
